### ISSUE TITLE
GetChannelList()

### ISSUE THREAD

**Issue by ghost** [Itarater/XRP#11]
There were some changes to GetChannelList() returns in a recent minor build which are causing issues with chat config along with popping up with an error when Interface options are opened.

> <Funkeh\`\> hey TheDanW did something change with GetChannelList() in the minor build?
> <TheDanW\> i don't think so
> <TheDanW\> oh yeah, it returns an extra bool now, whether or not the channel is disabled
> <Funkeh\`\> TheDanW: damn, API breakage in a minor build
> <Funkeh\`\> causing issues with a library used across many addons =P
> <Simca_\> i mean, an extra return on the end isn't breakage unless you're using a weird method of defining way too many variables in a line to save slightly on vertical space
> <Simca_\> i.e. you are foxlit
> <Funkeh\`\> it's not an extra return on the end
> <Simca_\> oh.
> <Simca_\> nevermind.
> <Funkeh\`\> it breaks the order entirely
> <Funkeh\`\> so it would return "1", "General", "2", "Trade"
> <Funkeh\`\> now it's returning "1", "General", false, "2"...

I am not sure if this is an intentional and/or permanent change, but it may need to be accounted for. Currently, when I am in more than one channel, it attempts to parse 2 as a channel name and aborts there (note that it returns an actual number value, and not a number in a string, unlike what was mistakenly implied.)

**Comment by Itarater** [comment]
It only breaks the ability to enable/disable RP names in various chat channels, so I'll give it a few days before fixing it. Just in case they break it again in reverse or something stupid.

**Comment by Itarater** [comment]
Closing, this is fixed in v2.0.0.
