### ISSUE TITLE
Random LUA error

### ISSUE THREAD

**Issue by Wyr3d** [Itarater/XRP#14]
Message: Interface\AddOns\XRP\Interface\Options\Chat.lua:60: attempt to index local 'name' (a number value)
Time: Mon Aug 13 14:16:08 2018
Count: 1
Stack: Interface\AddOns\XRP\Interface\Options\Chat.lua:60: attempt to index local 'name' (a number value)
[C]: in function `xpcall'
Interface\AddOns\XRP\Interface\Options\Templates.lua:62: in function <Interface\AddOns\XRP\Interface\Options\Templates.lua:58>
[C]: in function `pcall'
Interface\FrameXML\InterfaceOptionsFrame.lua:221: in function <Interface\FrameXML\InterfaceOptionsFrame.lua:220>
[C]: in function `securecall'
Interface\FrameXML\InterfaceOptionsFrame.lua:308: in function `InterfaceOptionsOptionsFrame_RefreshAddOns'
Interface\FrameXML\InterfaceOptionsFrame.lua:396: in function <Interface\FrameXML\InterfaceOptionsFrame.lua:387>
[C]: in function `Show'
Interface\FrameXML\InterfaceOptionsFrame.lua:204: in function `InterfaceOptionsFrame_Show'
Interface\FrameXML\InterfaceOptionsFrame.lua:485: in function `InterfaceOptionsFrame_OpenToCategory'
Interface\AddOns\MogIt\Core\GUI.lua:952: in function <Interface\AddOns\MogIt\Core\GUI.lua:948>

Locals: <none>

**Comment by Itarater** [comment]
Duplicate of #11
