### ISSUE TITLE
Unable to switch profiles.

### ISSUE THREAD

**Issue by Keazra** [Itarater/XRP#15]
A very simple report: I've recently switched servers on one of my characters, and ever since, I've been unable to switch my profiles.

I'm not sure if this coincided with the server move or with BFA, but either way, profile switching simply doesn't work anymore.

**Comment by Itarater** [comment]
Enable Lua errors (`/console scriptErrors 1`), reload your UI (`/reload`), and try again.

If there are any Lua errors referencing XRP, please provide them. (If there are Lua errors not referencing XRP, you should update any referenced addons, but that is unlikely to cause problems with XRP.) Once you're finished this testing, you can disable Lua errors again (`/console scriptErrors 0`).

If there are no errors, then I'll need a copy of your saved variables file for XRP to investigate, but I can walk you through providing that later, if it's necessary.

**Comment by Keazra** [comment]
Ah, yep, that's the issue. When I turned off profile parenting, my profiles started switching again.

Thanks!

**Comment by Itarater** [comment]
Closing, this is fixed in v2.0.0.
